In [1]:
import numpy as np
import pandas as pd

In [8]:
index=pd.MultiIndex.from_product([[2013,2014],[1,2]],names=['year','visit'])
columns=pd.MultiIndex.from_product([['bob','guido','sue'],['hr','temp']],names=['names','dept'])
data=np.round(np.random.randn(4,6),1)
health_data=pd.DataFrame(data,index=index,columns=columns)
print(health_data)

names       bob      guido       sue
dept         hr temp    hr temp   hr temp
year visit
2013 1     -0.1 -1.2  -0.8 -2.0  0.0  0.9
     2     -1.0 -1.2  -0.9  0.1 -0.3  0.4
2014 1     -0.7 -0.2  -0.5  0.9 -1.4  0.4
     2      1.4 -0.6  -0.0 -0.8  0.8 -0.7

In [9]:
health_data['guido']

dept         hr  temp
year visit
2013 1     -0.8  -2.0
     2     -0.9   0.1
2014 1     -0.5   0.9
     2     -0.0  -0.8

In [12]:
health_data['guido','hr']

year  visit
2013  1       -0.8
      2       -0.9
2014  1       -0.5
      2       -0.0
Name: (guido, hr), dtype: float64

In [13]:
health_data.iloc[:2,:2]

names       bob
dept         hr temp
year visit
2013 1     -0.1 -1.2
     2     -1.0 -1.2

In [14]:
health_data.loc[:,('bob','hr')]

year  visit
2013  1       -0.1
      2       -1.0
2014  1       -0.7
      2        1.4
Name: (bob, hr), dtype: float64

In [15]:
idx=pd.IndexSlice
health_data.loc[idx[:,1],idx[:,'hr']]

names       bob guido  sue
dept         hr    hr   hr
year visit
2013 1     -0.1  -0.8  0.0
2014 1     -0.7  -0.5 -1.4

In [17]:
index=pd.MultiIndex.from_product([['a','c','b'],[1,2]])
data=pd.Series(np.random.rand(6),index=index)
data.index.names=['char','int']
data

char  int
a     1      0.644808
      2      0.518513
c     1      0.473630
      2      0.730002
b     1      0.290841
      2      0.848927
dtype: float64

In [18]:
try:
    data['a':'b']
except Exception as e:
    print(type(e))
    print(e)

<class 'pandas.errors.UnsortedIndexError'>
'Key length (1) was greater than MultiIndex lexsort depth (0)'

In [19]:
data=data.sort_index()
data

char  int
a     1      0.644808
      2      0.518513
b     1      0.290841
      2      0.848927
c     1      0.473630
      2      0.730002
dtype: float64

In [20]:
data['a':'b']

char  int
a     1      0.644808
      2      0.518513
b     1      0.290841
      2      0.848927
dtype: float64

In [21]:
health_data

names       bob      guido       sue
dept         hr temp    hr temp   hr temp
year visit
2013 1     -0.1 -1.2  -0.8 -2.0  0.0  0.9
     2     -1.0 -1.2  -0.9  0.1 -0.3  0.4
2014 1     -0.7 -0.2  -0.5  0.9 -1.4  0.4
     2      1.4 -0.6  -0.0 -0.8  0.8 -0.7

In [31]:
data_mean=health_data.mean()
print(data_mean)
data_mean.mean()

names  dept
bob    hr     -0.100
       temp   -0.800
guido  hr     -0.550
       temp   -0.450
sue    hr     -0.225
       temp    0.250
dtype: float64

-0.3125

In [35]:
data_mean.groupby(level='year').mean()

KeyError: 'Level year not found'