In [3]:
import numpy as np
import pandas as pd

In [4]:
index=[['A',2010],['A',2020],['A',2025],['B',2010],['B',2020],['B',2025]]
population=[123,456,789,102,203,304]
i=pd.MultiIndex.from_tuples(index,names=['Country','Year'])
print(i)
pop=pd.Series(population,index=i)
print(pop)

MultiIndex([('A', 2010),
            ('A', 2020),
            ('A', 2025),
            ('B', 2010),
            ('B', 2020),
            ('B', 2025)],
           names=['Country', 'Year'])
Country  Year
A        2010    123
         2020    456
         2025    789
B        2010    102
         2020    203
         2025    304
dtype: int64

In [5]:
index=[['A',2010],['A',2020],['A',2025],['B',2010],['B',2020],['B',2025]]
population=[1.5,1.7,1.9,2.5,2.7,2.9]
i=pd.MultiIndex.from_product(index)
print(i)

MultiIndex([( 'A',  'A',  'A',  'B',  'B',  'B'),
            ( 'A',  'A',  'A',  'B',  'B', 2025),
            ( 'A',  'A',  'A',  'B', 2020,  'B'),
            ( 'A',  'A',  'A',  'B', 2020, 2025),
            ( 'A',  'A',  'A', 2010,  'B',  'B'),
            ( 'A',  'A',  'A', 2010,  'B', 2025),
            ( 'A',  'A',  'A', 2010, 2020,  'B'),
            ( 'A',  'A',  'A', 2010, 2020, 2025),
            ( 'A',  'A', 2025,  'B',  'B',  'B'),
            ( 'A',  'A', 2025,  'B',  'B', 2025),
            ( 'A',  'A', 2025,  'B', 2020,  'B'),
            ( 'A',  'A', 2025,  'B', 2020, 2025),
            ( 'A',  'A', 2025, 2010,  'B',  'B'),
            ( 'A',  'A', 2025, 2010,  'B', 2025),
            ( 'A',  'A', 2025, 2010, 2020,  'B'),
            ( 'A',  'A', 2025, 2010, 2020, 2025),
            ( 'A', 2020,  'A',  'B',  'B',  'B'),
            ( 'A', 2020,  'A',  'B',  'B', 2025),
            ( 'A', 2020,  'A',  'B', 2020,  'B'),
            ( 'A', 2020,  'A',  'B', 2020, 2025),
            ( 'A', 2020,  'A', 2010,  'B',  'B'),
            ( 'A', 2020,  'A', 2010,  'B', 2025),
            ( 'A', 2020,  'A', 2010, 2020,  'B'),
            ( 'A', 2020,  'A', 2010, 2020, 2025),
            ( 'A', 2020, 2025,  'B',  'B',  'B'),
            ( 'A', 2020, 2025,  'B',  'B', 2025),
            ( 'A', 2020, 2025,  'B', 2020,  'B'),
            ( 'A', 2020, 2025,  'B', 2020, 2025),
            ( 'A', 2020, 2025, 2010,  'B',  'B'),
            ( 'A', 2020, 2025, 2010,  'B', 2025),
            ( 'A', 2020, 2025, 2010, 2020,  'B'),
            ( 'A', 2020, 2025, 2010, 2020, 2025),
            (2010,  'A',  'A',  'B',  'B',  'B'),
            (2010,  'A',  'A',  'B',  'B', 2025),
            (2010,  'A',  'A',  'B', 2020,  'B'),
            (2010,  'A',  'A',  'B', 2020, 2025),
            (2010,  'A',  'A', 2010,  'B',  'B'),
            (2010,  'A',  'A', 2010,  'B', 2025),
            (2010,  'A',  'A', 2010, 2020,  'B'),
            (2010,  'A',  'A', 2010, 2020, 2025),
            (2010,  'A', 2025,  'B',  'B',  'B'),
            (2010,  'A', 2025,  'B',  'B', 2025),
            (2010,  'A', 2025,  'B', 2020,  'B'),
            (2010,  'A', 2025,  'B', 2020, 2025),
            (2010,  'A', 2025, 2010,  'B',  'B'),
            (2010,  'A', 2025, 2010,  'B', 2025),
            (2010,  'A', 2025, 2010, 2020,  'B'),
            (2010,  'A', 2025, 2010, 2020, 2025),
            (2010, 2020,  'A',  'B',  'B',  'B'),
            (2010, 2020,  'A',  'B',  'B', 2025),
            (2010, 2020,  'A',  'B', 2020,  'B'),
            (2010, 2020,  'A',  'B', 2020, 2025),
            (2010, 2020,  'A', 2010,  'B',  'B'),
            (2010, 2020,  'A', 2010,  'B', 2025),
            (2010, 2020,  'A', 2010, 2020,  'B'),
            (2010, 2020,  'A', 2010, 2020, 2025),
            (2010, 2020, 2025,  'B',  'B',  'B'),
            (2010, 2020, 2025,  'B',  'B', 2025),
            (2010, 2020, 2025,  'B', 2020,  'B'),
            (2010, 2020, 2025,  'B', 2020, 2025),
            (2010, 2020, 2025, 2010,  'B',  'B'),
            (2010, 2020, 2025, 2010,  'B', 2025),
            (2010, 2020, 2025, 2010, 2020,  'B'),
            (2010, 2020, 2025, 2010, 2020, 2025)],
           )

In [6]:
index=[['A',2010],['A',2020],['A',2025],['B',2010],['B',2020],['B',2025]]
population=[123,456,789,102,203,304]
i1=pd.MultiIndex.from_arrays([['A','A','A','B','B','B'],[2010,2020,2025,2010,2020,2025]],names=['Country','Year'])
print(i1)
pop=pd.Series(population,index=i1)
print(pop)

MultiIndex([('A', 2010),
            ('A', 2020),
            ('A', 2025),
            ('B', 2010),
            ('B', 2020),
            ('B', 2025)],
           names=['Country', 'Year'])
Country  Year
A        2010    123
         2020    456
         2025    789
B        2010    102
         2020    203
         2025    304
dtype: int64

In [7]:
i2=pd.MultiIndex.from_product([['A','B'],[2010,2020,2025]],names=['Country','Year'])
print(i2)

MultiIndex([('A', 2010),
            ('A', 2020),
            ('A', 2025),
            ('B', 2010),
            ('B', 2020),
            ('B', 2025)],
           names=['Country', 'Year'])

In [8]:
l3=pd.MultiIndex(levels=[['A','B'],[2010,2020,2025]],codes=[[0,0,0,1,1,1],[0,1,2,0,1,2]],names=['Country','Year'])
print(l3)

MultiIndex([('A', 2010),
            ('A', 2020),
            ('A', 2025),
            ('B', 2010),
            ('B', 2020),
            ('B', 2025)],
           names=['Country', 'Year'])

In [9]:
print(pop)
print(pop['A',2010])
print(pop['A'])
print(pop[:,2010])
print(pop[pop>200])

Country  Year
A        2010    123
         2020    456
         2025    789
B        2010    102
         2020    203
         2025    304
dtype: int64
123
Year
2010    123
2020    456
2025    789
dtype: int64
Country
A    123
B    102
dtype: int64
Country  Year
A        2020    456
         2025    789
B        2020    203
         2025    304
dtype: int64

In [10]:
index=pd.MultiIndex.from_product([[2013,2014],[1,2]],names=['Country','Year'])
columns=pd.MultiIndex.from_product([['A','B'],['Maths','Science']],names=['Subject','Course'])
print(columns)

MultiIndex([('A',   'Maths'),
            ('A', 'Science'),
            ('B',   'Maths'),
            ('B', 'Science')],
           names=['Subject', 'Course'])

In [11]:
#create a data frame as a marks and grade for 3 different couses for 5 different students 
np.random.seed(0)
marks = np.random.randint(50,100,size=(5,3))
df = pd.DataFrame(marks,columns=['Maths','Science','English'],index=['Student1','Student2','Student3','Student4','Student5'])
print(df)

          Maths  Science  English
Student1     94       97       50
Student2     53       53       89
Student3     59       69       71
Student4     86       73       56
Student5     74       74       62

## 15th october

In [12]:
pop.unstack(level=0)

Country    A    B
Year
2010     123  102
2020     456  203
2025     789  304

In [13]:
pop.unstack(level=1)

Year     2010  2020  2025
Country
A         123   456   789
B         102   203   304

In [14]:
pop.unstack().stack()

Country  Year
A        2010    123
         2020    456
         2025    789
B        2010    102
         2020    203
         2025    304
dtype: int64

In [15]:
pop_flate=pop.reset_index(name='population')
pop_flate

  Country  Year  population
0       A  2010         123
1       A  2020         456
2       A  2025         789
3       B  2010         102
4       B  2020         203
5       B  2025         304

In [16]:
pop_flate.set_index(['Country','Year'])

              population
Country Year
A       2010         123
        2020         456
        2025         789
B       2010         102
        2020         203
        2025         304